Repository 66022523/MIXIT, pull requests merged in 2025-03, with the labels that each got.

#15 🖼️ Add SEO link icon.
  app/layout.jsx
Labels: enhancement

#20 🔨 Fix sign-in and sign-up redirect.
  components/forms/authentication/social.jsx
Labels: bug

#21 🔨 Fix Social Auth Issues.
  components/forms/authentication/social.jsx
Labels: bug, enhancement
